### ISSUE TITLE
javascript errors after successful deploy

### ISSUE THREAD

**Issue by israelcurtis** [JamieGoodson/gatefold#2]
followed the docs, all the installs seemed to go well, netlify app was built and deployed, but when i visit the site, page is just black (even though I am connected to raspotify and playing fine). Safari Console shows the error:

```
[Error] Unhandled Promise Rejection: TypeError: l.createConnection is not a function. (In 'l.createConnection(e,n)', 'l.createConnection' is undefined)
	h (2.41c953f5.js:1:37765)
	(anonymous function) (2.41c953f5.js:1:15692)
	X (2.41c953f5.js:1:15392)
	r (2.41c953f5.js:1:48138)
	Sr (2.41c953f5.js:2:13746)
	(anonymous function) (2.41c953f5.js:15:4507)
	(anonymous function) (2.41c953f5.js:15:4533)
	map
	(anonymous function) (index.6519ee2d.js:1:4004)
	M (scheduler.54bbbd53.js:1:1827)
	$e (index.6519ee2d.js:1:5075)
	re (app.d86eecd8.js:1:4890)
	Oe (start.ebe3f2e3.js:1:8253)
	(anonymous function) (start.ebe3f2e3.js:1:22089)
```

in Chrome console error shows:

```
Connecting to MQTT broker at undefined
2.41c953f5.js:1 Uncaught (in promise) TypeError: l.createConnection is not a function
    at Object.h (2.41c953f5.js:1:37748)
    at X.m [as streamBuilder] (2.41c953f5.js:1:48118)
    at X._setupStream (2.41c953f5.js:1:15678)
    at new X (2.41c953f5.js:1:15379)
    at Function.r [as connect] (2.41c953f5.js:1:48132)
    at Sr (2.41c953f5.js:2:13738)
    at 2.41c953f5.js:15:4504
    at E (scheduler.54bbbd53.js:1:88)
    at Array.map (<anonymous>)
    at index.6519ee2d.js:1:4000
```

live site is https://raspotify-gatefold.netlify.app

**Comment by israelcurtis** [comment]
nvm - not sure what changed (I didn't touch a thing), but a manual redeploy in Netlify seems to have solved it!

**Comment by JamieGoodson** [comment]
@israelcurtis Glad you got it working!
